DEFAULT_LOGGING_LEVEL = "DEBUG"
DEFAULT_SERVER_INTERFACE = "0.0.0.0"
DEFAULT_SERVER_PORT = 10000

DEFAULT_BACKEND_URL = "http://localhost:8080/v1"
DEFAULT_WRITER_URL = "http://localhost:8083/api/v1/"
DEFAULT_WRITER_INSTANCE_NAME = "writer"
DEFAULT_VALIDATION_MODULE = "detector_integration_api.validation.debug"

BACKEND_URL_SUFFIX = "/v1"
