package:
    name: detector_integration_api
    version: 0.0.4

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bottle
        - requests
        - mflow_nodes

build:
  entry_points:
    - detector_api_server = detector_integration_api.start_server:main

about:
    home: git@git.psi.ch:HPDI/integration_rest_api.git
