package:
    name: detector_integration_api
    version: 1.7.0

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bottle
        - requests
        - mflow_nodes >=1.3.0

about:
    home: https://github.com/datastreaming/detector_integration_api
